import cppchess
import chess

ruy_lopez = chess.Board()
ruy_lopez.push_san("e4")
ruy_lopez.push_san("e5")
ruy_lopez.push_san("Nf3")
ruy_lopez.push_san("Nc6")
ruy_lopez.push_san("Bb5")
ruy_lopez.push_san("a6")
ruy_lopez.push_san("Ba4")
ruy_lopez.push_san("Nf6")

ruy_lopez_cpp = cppchess.Board()
ruy_lopez_cpp.push_san("e4")
ruy_lopez_cpp.push_san("e5")
ruy_lopez_cpp.push_san("Nf3")
ruy_lopez_cpp.push_san("Nc6")
ruy_lopez_cpp.push_san("Bb5")
ruy_lopez_cpp.push_san("a6")
ruy_lopez_cpp.push_san("Ba4")
ruy_lopez_cpp.push_san("Nf6")

scholars_mate = chess.Board()
scholars_mate.push_san("e4")
scholars_mate.push_san("e5")
scholars_mate.push_san("Qh5")
scholars_mate.push_san("Nc6")
scholars_mate.push_san("Bc4")
scholars_mate.push_san("Nf6")
#scholars_mate.push_san("Qxf7")

scholars_mate_cpp = cppchess.Board()
scholars_mate_cpp.push_san("e4")
scholars_mate_cpp.push_san("e5")
scholars_mate_cpp.push_san("Qh5")
scholars_mate_cpp.push_san("Nc6")
scholars_mate_cpp.push_san("Bc4")
scholars_mate_cpp.push_san("Nf6")
#scholar_mate_cpp.push_san("Qxf7")

single_move = chess.Board()
single_move.push_san("e4")
single_move.push_san("e5")
single_move.push_san("Nf3")
single_move.push_san("Nc6")
single_move.push_san("Bc4")
single_move.push_san("Nce7")
single_move.push_san("Bxf7")

single_move_cpp = cppchess.Board()
single_move_cpp.push_san("e4")
single_move_cpp.push_san("e5")
single_move_cpp.push_san("Nf3")
single_move_cpp.push_san("Nc6")
single_move_cpp.push_san("Bc4")
single_move_cpp.push_san("Nce7")
single_move_cpp.push_san("Bxf7")